-- phpMyAdmin SQL Dump
-- version 4.9.5
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Generation Time: Dec 17, 2020 at 11:37 AM
-- Server version: 10.4.14-MariaDB
-- PHP Version: 7.3.23

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `tshu2_dmit2025`
--

-- --------------------------------------------------------

--
-- Table structure for table `recipeapp`
--

CREATE TABLE `recipeapp` (
  `title` varchar(200) NOT NULL,
  `author` varchar(200) NOT NULL,
  `difficulty_level` varchar(50) NOT NULL,
  `prep_time` int(100) NOT NULL,
  `cook_time` int(100) NOT NULL,
  `total_time` int(100) NOT NULL,
  `servings` int(100) NOT NULL,
  `ingredients` text NOT NULL,
  `directions` text NOT NULL,
  `resp_description` text NOT NULL,
  `source` text NOT NULL,
  `picture` varchar(255) NOT NULL,
  `id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `recipeapp`
--

INSERT INTO `recipeapp` (`title`, `author`, `difficulty_level`, `prep_time`, `cook_time`, `total_time`, `servings`, `ingredients`, `directions`, `resp_description`, `source`, `picture`, `id`) VALUES
('Chickpea Salad Sandwiches', 'Food Network Kitchen', 'Easy', 0, 15, 15, 2, 'One 15-ounce can chickpeas, drained and rinsed\r\n3 tablespoons mayonnaise or vegan mayonnaise spread\r\n1 tablespoon fresh lemon juice\r\n1 tablespoon roughly chopped fresh dill\r\n2 teaspoons capers\r\n1 1/2 teaspoons stone-ground mustard\r\n1/2 teaspoon ground turmeric\r\nKosher salt and freshly ground black pepper\r\n2 tablespoons roasted unsalted pepitas\r\n1 cup lightly packed baby kale\r\n4 slices whole wheat bread, toasted', 'Mash the chickpeas, mayonnaise, lemon juice, dill, capers, mustard, turmeric, 1/2 teaspoon salt and several grinds of pepper in a large bowl with a fork or potato masher until beans are crushed and mixture is slightly chunky, scrapping down the sides of the bowl with a rubber spatula as needed. Taste and adjust the seasoning with salt and pepper.\r\nSpread the salad onto 2 pieces of toasted whole wheat bread, top with toasted pepitas and baby kale and then sandwich with the remaining 2 pieces of bread. Serve immediately.', 'Quick and delicious chickpea salad sandwich.', 'https://www.foodnetwork.com/recipes/food-network-kitchen/chickpea-salad-sandwiches-8811083', '5fdb908f9e47e.jpeg', 36),
('Healthy Peanut Soba Noodles with Vegetable Salad', 'Food Network Kitchen', 'Easy', 10, 25, 35, 1, 'Kosher salt and freshly ground black pepper\r\n2 ounces soba (buckwheat) noodles\r\n1 tablespoon plus 1 1/2 teaspoons smooth peanut butter\r\n1 teaspoon hoisin sauce\r\n1/2 teaspoon chili-garlic sauce\r\n1 tablespoon plus 1 teaspoon lime juice (from about 1 lime)\r\n1 teaspoon toasted sesame oil\r\n1/2 cup prepared coleslaw mix or thinly sliced green cabbage\r\n2 tablespoons fresh cilantro leaves\r\n1 scallion, thinly sliced\r\n1/2 orange, red or yellow bell pepper, cut into thin strips\r\n1/2 Persian cucumber, halved and cut into thin strips\r\n2 sheets roasted seaweed snacks, cut into thin strips', 'Bring a small pot of salted water to a boil. Add the soba noodles and cook according to the package instructions. Reserve 2 tablespoons of the cooking water, then drain the noodles and cool.\r\nWhisk together the peanut butter, hoisin, chili-garlic sauce, 1 tablespoon of the lime juice, 1/2 teaspoon of the sesame oil, the reserved 2 tablespoons noodle water and a large pinch salt in a medium bowl. Add the soba noodles to the sauce and toss to coat. Transfer the tossed noodles to a 32-ounce resealable plastic container or glass jar. \r\nWhisk together the remaining 1 teaspoon lime juice, 1/2 teaspoon sesame oil, a pinch salt and a few grinds of black pepper in the same bowl. Add the coleslaw mix, cilantro, scallion, bell pepper and cucumber and toss to coat. Transfer to the container on top of the noodles. Pack the seaweed snacks separately. \r\nWhen ready to eat, top with the seaweed snack strips and eat right out of the container (or transfer to a bowl).', 'Colorful and very delicious peanut soba noodles with vegetable salad.', 'https://www.foodnetwork.com/recipes/food-network-kitchen/healthy-peanut-soba-noodles-with-vegetable-salad-3686266', '5fdb916e43925.jpeg', 37),
('Cheddar and Apple Grilled Cheese Sandwiches', 'Food Network Kitchen', 'Easy', 5, 10, 15, 2, '4 slices sourdough bread\r\n6 slices sharp Cheddar, about 3 ounces\r\nHalf apple, cored and thinly sliced\r\n2 tablespoon unsalted butter', 'Put 2 slices of bread on a cutting board or work surface. Top each with two slices of cheese, the apple slices, a third slice of cheese and another piece of bread. Press down lightly.\r\nHeat 1 tablespoon butter in a large skillet over medium-low heat. Add the sandwiches and cook until the bread toasts and the cheese is slightly melted, 3 to 5 minutes. Flip with a spatula and add the remaining tablespoon of butter to the pan. Cook until the other side is toasted and the cheese is melted, about 3 minutes more, adjusting the heat as needed to keep the bread from burning before the cheese melts.?', 'The classic combination of tart apples and savory Cheddar transform a basic grilled cheese into a sophisticated sandwich.\r\n', 'https://www.foodnetwork.com/recipes/food-network-kitchen/cheddar-and-apple-grilled-cheese-sandwiches-5496992', '5fdb9231c2fa8.jpeg', 38),
('Mediterranean Tuna Wrap', 'Ellie Krieger', 'Easy', 0, 13, 13, 4, '2 (6-ounce) cans chunk light tuna in water, drained well\r\n1/4 cup finely diced red onion\r\n1/4 cup chopped fresh parsley leaves\r\n1/4 cup chopped calamata olives\r\n3 tablespoons olive oil\r\n1/2 teaspoon lemon zest\r\n2 tablespoons freshly squeezed lemon juice\r\nSalt\r\nFreshly ground black pepper\r\n6 cups pre-washed mixed greens (about 3 ounces)\r\n4 whole-grain wrap breads (about 2 ounces each)\r\n2 large tomatoes, sliced', 'In a medium bowl combine the tuna, onion, parsley, olives.\r\nIn a small bowl, whisk together the olive oil, zest, lemon juice, salt and pepper. Pour about 2/3 the dressing over the tuna mixture and toss to combine. In a separate bowl, pour the rest of the dressing over the greens and toss to combine.\r\nPlace some tuna salad onto each piece of wrap bread. Top with 1 1/2 cups of greens and a few tomato slices. Roll the wraps and serve.', 'Fast and delicious tuna wrap.', 'https://www.foodnetwork.com/recipes/ellie-krieger/mediterranean-tuna-wrap-recipe-1947830', '5fdb92ef04203.jpeg', 39),
('Ravioli with Lemon, Peas and Pancetta', 'Food Network Magazine', 'Easy', 5, 20, 25, 4, 'Kosher salt\r\n2 ounces thinly sliced pancetta (8 to 10 slices)\r\n2 10-ounce packages spinach-ricotta ravioli\r\n6 tablespoons unsalted butter\r\n2 teaspoons finely grated lemon zest, plus 1 teaspoon lemon juice\r\n1 cup frozen peas, thawed\r\n1/4 cup grated pecorino-romano cheese, plus more for topping\r\nFreshly ground pepper\r\nChopped fresh basil, for topping', 'Bring a large pot of salted water to a boil. Meanwhile, cook the pancetta in a large nonstick skillet over medium-high heat, turning, until browned and crisp, 8 to 10 minutes. Remove to a paper towelâ€“lined plate and wipe out the skillet.\r\nAdd the ravioli to the boiling water and cook as the label directs. Reserve 1/2 cup cooking water, then drain gently.\r\nCombine the butter and lemon zest and juice in the reserved skillet over medium heat. Add the peas, ravioli and 1/4 cup of the reserved cooking water; toss to coat. Stir in the pecorino and toss. Season with salt and pepper. Add more cooking water, 1 tablespoon at a time, to loosen.\r\nDivide the ravioli, peas and any sauce among shallow bowls. Sprinkle with more pecorino. Crumble the pancetta and scatter over the ravioli. Top with basil.', 'Quick and easy ravioli with lemon, peas and pancetta.', 'https://www.foodnetwork.com/recipes/food-network-kitchen/ravioli-with-lemon-peas-and-pancetta-8583643', '5fdb94130ab0a.jpeg', 40),
('Peppercorn Roasted Beef Tenderloin', 'Ree Drummond', 'Easy', 40, 5, 45, 10, '1 whole beef tenderloin, trimmed of all visible fat\r\nKosher salt\r\n2 teaspoons sugar\r\n1/2 cup tri-color peppercorns, crushed with a rolling pin\r\n1 stick butter\r\n2 cloves garlic, crushed', 'Preheat the oven to 475 degrees F.\r\nPlace the tenderloin on a roasting rack. Sprinkle generously with kosher salt and sugar, which will deepen the savory flavors.\r\nPress the crushed peppercorns all over the surface of the meat. Insert a meat thermometer and place in the oven until the beef registers 120 to 125 degrees F for medium-rare/rare. Beef will probably cook in 20 to 25 minutes depending on its temp before it goes in the oven.\r\nWhile the meat is roasting, melt the butter with the garlic in a small skillet, and allow the butter to slightly brown. Remove the garlic and discard.\r\nRemove the meat when it\'s done and pour the garlic butter over gently (it should sizzle when it hits the meat). Cover the meat loosely with foil and allow to rest for 10 minutes before slicing.', 'Tender and delicious peppercorn roasted beef.', 'https://www.foodnetwork.com/recipes/ree-drummond/peppercorn-roasted-beef-tenderloin-recipe-2070890', '5fdb950cf1044.jpeg', 41),
('Sunday Supper Stuffed Pork Chops, Cream Cheese Potatoes, Sugar Snap Peas', 'Rachael Ray', 'Intermediate', 15, 25, 40, 4, '2 1/2 pounds potatoes, peeled and cut into chunks\r\nSalt\r\n1/2 cup milk\r\n4 ounces cream cheese\r\n1 small onion finely chopped\r\n2 tablespoons chopped fresh chives, optional\r\n1 tablespoon olive oil or vegetable oil, plus some for drizzling\r\n2 slices bacon, chopped\r\n1 small McIntosh apple, chopped\r\n2 ribs celery from the heart, finely chopped\r\n1 small onion, chopped\r\n2 tablespoons freshly chopped sage leaves, or 1 teaspoon ground dried sage\r\n2 tablespoons freshly chopped thyme leaves, or 1 teaspoon dried leaves\r\nFreshly ground black pepper\r\n2 store bought corn muffins\r\n8 thin boneless center cut pork loin chops\r\n2 pounds sugar snap peas\r\n1 cup chicken broth or water\r\n1 tablespoon butter', 'Cover potatoes with water and season with salt. Cover pan to bring potatoes to a quick boil. Boil potatoes until tender, about 12 minutes. Drain potatoes and return them to the hot pot to dry. Set aside. Heat milk, cream cheese and onion over medium low heat until cream cheese melts into milk and mixture bubbles. Pour hot milk and cream cheese into the potatoes and mash to desired consistency. Add a little extra milk for softer potatoes. Season with salt, to your taste, and transfer to a serving dish. Garnish with chopped chives.\r\nPreheat a medium skillet over medium high heat. Add oil and bacon to the skillet and cook 2 minutes. Add apple, celery and onion and season the mixture with herbs, salt and pepper. Reduce heat to medium. Cook vegetables 5 minutes, stirring frequently. Crumble the corn muffins into the pan and combine stuffing.\r\nPreheat a large skillet or grill pan over medium high heat. Drizzle chops with oil and season with salt and pepper. Cook chops 3 to 4 minutes on each side. Do not over cook. The chops should be firm but still giving off juices.\r\nIn a medium saucepan, place snap peas and broth and 1 tablespoon butter over medium high heat. When the liquid boils, cover the pan and reduce heat to low. Simmer snap peas 3 to 5 minutes, until tender but still green. Remove pan from heat and season snap peas with salt, to taste.\r\nTo assemble stuffed chops, set a thin chop on dinner plate or serving plate. Mound the pork chop with stuffing, allowing some to spill onto the plate, then top with a second chop. Repeat with 3 remaining servings. Pass potatoes and snap peas to complete the meal.', 'Challenging but very delicious pork supper recipe.', 'https://www.foodnetwork.com/recipes/rachael-ray/sunday-supper-stuffed-pork-chops-cream-cheese-potatoes-sugar-snap-peas-recipe-1941246', '5fdb9699da04e.jpeg', 42),
('Ranch Pork Chop Sheet Pan Supper', 'Ree Drummond', 'Easy', 25, 10, 35, 4, '2 tablespoons honey\r\n2 tablespoons Worcestershire sauce \r\nOne 3.5-ounce packet ranch dressing mix \r\n5 tablespoons olive oil \r\n1 1/2 teaspoons freshly ground black pepper \r\n4 boneless pork chops (1/2 inch thick) \r\n1 pound baby Yukon gold potatoes, halved \r\n8 ounces green beans, trimmed \r\n2 tablespoons fresh parsley leaves', 'Preheat the oven to 475 degrees F.\r\nIn a small bowl, mix together the honey, Worcestershire, 2 tablespoons of the ranch dressing mix, 2 tablespoons of the olive oil and 1 teaspoon of the pepper until combined.\r\nBrush the mixture over the chops on both sides and place in a row on one side of a sheet pan using tongs.\r\nIn a medium mixing bowl, add the potatoes, 2 tablespoons of olive oil, 1 tablespoon of the ranch dressing mix and 1/4 teaspoon of pepper and toss to coat. Tip onto the middle of the sheet pan next to the pork chops. Bake for 15 minutes.\r\nMeanwhile, add the beans to a bowl along with the remaining olive oil, ranch mix and 1/4 teaspoon pepper and toss.\r\nWhen the 15 minutes is up, remove the sheet pan from the oven and flip the pork chops. Toss the potatoes and add the green beans to the empty space at the side of the baking sheet. Bake until the vegetables are just beginning to brown, about 7 minutes more. Garnish with the parsley leaves and serve.', 'Delicious ranch pork chops', 'https://www.foodnetwork.com/recipes/ree-drummond/ranch-pork-chop-sheet-pan-supper-5399499', '5fdb97da80d8e.jpeg', 43),
('Pesto Chicken Skillet Supper', 'Ree Drummond', 'Easy', 0, 16, 16, 4, '2 boneless, skinless chicken breasts, cut into 1/2-inch cubes\r\nKosher salt and freshly ground black pepper \r\n2 tablespoons olive oil \r\n1 small red onion, thinly sliced\r\n1 large zucchini, halved and sliced into 1/4-inch half-moons \r\n1 large summer squash, halved and sliced into 1/4-inch half-moons \r\n2 cups chopped kale \r\n1/2 cup yellow cherry tomatoes, halved \r\n1/2 cup red grape tomatoes, halved \r\n2 ears corn, shucked and kernels removed\r\n2 cloves garlic, minced \r\n1/4 cup store-bought basil pesto\r\n1/4 cup heavy cream \r\nJuice of 1/2 lemon \r\nOne 5-ounce Parmesan wedge, grated', 'Heat a large skillet over medium-high heat.\r\nSeason the chicken with salt and pepper. Add the olive oil to the skillet, throw in the chicken and brown on all sides, 4 to 5 minutes. Remove and reserve.\r\nAdd the onions, zucchini and squash and cook, stirring occasionally, for 2 to 3 minutes. Move those vegetables to the edges of the skillet and add the kale, tomatoes, corn and garlic. Cook, stirring occasionally, until the kale turns bright green, an additional, 1 to 2 minutes.\r\nIn a small bowl, stir together the pesto and cream.\r\nReturn the chicken to the skillet along with any juices. Add the pesto cream and reduce the heat to medium. Cook, stirring, for an additional 1 to 2 minutes. Remove from the heat and stir in the lemon juice and grated Parmesan. Enjoy.', 'Easy pesto chicken skillet recipe perfect for supper.', 'https://www.foodnetwork.com/recipes/ree-drummond/pesto-chicken-skillet-supper-5296954', '5fdb98dd9ee90.jpeg', 44),
('Classic Deviled Eggs', 'Mary Nolan', 'Easy', 20, 15, 35, 4, '6 eggs\r\n1/4 cup mayonnaise\r\n1 teaspoon white vinegar\r\n1 teaspoon yellow mustard\r\n1/8 teaspoon salt\r\nFreshly ground black pepper\r\nSmoked Spanish paprika, for garnish', 'Place eggs in a single layer in a saucepan and cover with enough water that there\'s 1 1/2 inches of water above the eggs. Heat on high until water begins to boil, then cover, turn the heat to low, and cook for 1 minute. Remove from heat and leave covered for 14 minutes, then rinse under cold water continuously for 1 minute.\r\nCrack egg shells and carefully peel under cool running water. Gently dry with paper towels. Slice the eggs in half lengthwise, removing yolks to a medium bowl, and placing the whites on a serving platter. Mash the yolks into a fine crumble using a fork. Add mayonnaise, vinegar, mustard, salt, and pepper, and mix well.\r\nEvenly disperse heaping teaspoons of the yolk mixture into the egg whites. Sprinkle with paprika and serve.', 'Classic Deviled Eggs done in a flash', 'https://www.foodnetwork.com/recipes/classic-deviled-eggs-recipe-1911032', '5fdb99b174403.jpeg', 45),
('Christmas Pasta Salad', 'Food Network Kitchen', 'Easy', 0, 35, 35, 10, 'Kosher salt\r\n2 heads broccoli (about 1 1/2 pounds), cut into florets \r\n1 pound mezze rigatoni or other short tubular pasta  \r\n1/3 cup plus 2 tablespoons olive oil \r\n1 1/2 cups baby spinach \r\n1/2 cup freshly grated Parmesan (about 1 ounce) \r\n1/4 cup almonds \r\n1/4 cup packed fresh basil leaves \r\nJuice of 1 lemon (about 3 tablespoons) \r\n2 tablespoons chopped fresh chives, plus more for serving \r\n2 roasted red peppers, drained and sliced (about 1 1/2 cups) \r\n1/2 cup sun-dried tomatoes packed in oil, drained and thinly sliced  \r\n8 ounces small mozzarella balls (or pearls) \r\n2 tablespoons white wine vinegar', 'Bring a large pot of generously salted water to a boil. Fill a large bowl with cold water. Drop the broccoli into the boiling water and cook until crisp-tender and bright green, about 2 minutes. Remove with a slotted spoon and plunge into the cold water to stop the cooking. Let sit until cool, then drain and set aside.\r\nReturn the water in the pot to a boil and cook the rigatoni according to the package directions for al dente. Drain in a colander and transfer to a large bowl. Toss the pasta with 2 tablespoons of the olive oil to coat evenly and refrigerate until cooled completely, about 10 minutes.  \r\nMeanwhile, add the remaining 1/3 cup olive oil to a blender with the spinach, Parmesan, almonds, basil, lemon juice, chives and 1/4 cup water and puree until completely smooth. Pour the pesto over top of the pasta and add the reserved broccoli, red peppers, sun-dried tomatoes, mozzarella, vinegar and 1 teaspoon salt. Toss gently until well combined. Transfer to a serving bowl and sprinkle with more chopped chives. Cover and refrigerate until ready to serve, up to 4 hours.', 'Perfect pasta salad for Christmas', 'https://www.foodnetwork.com/recipes/food-network-kitchen/christmas-pasta-salad-7593101', '5fdb9c51b6eb9.jpeg', 46),
('Chicken Scampi Pasta', 'Food Network Kitchen', 'Easy', 0, 25, 25, 6, 'Kosher salt\r\n1 pound thinly-sliced chicken cutlets, cut into 1/2-inch-thick strips\r\n3 tablespoons olive oil \r\n8 tablespoons unsalted butter, cubed \r\n6 cloves garlic, sliced \r\n1/2 teaspoon crushed red pepper flakes \r\n1/2 cup dry white wine \r\n12 ounces angel hair pasta \r\n1 teaspoon lemon zest plus the juice of 1 large lemon \r\n1/2 cup freshly grated Parmesan\r\n1/2 cup chopped fresh Italian parsley', 'Bring a large pot of salted water to a boil for the pasta. Sprinkle the chicken with some salt. Heat a large skillet over medium-high heat until hot, then add the oil. Working in 2 batches, brown the chicken until golden but not cooked through, 2 to 3 minutes per batch. Remove the chicken to a plate.\r\nMelt 4 tablespoons of the butter in the skillet. Add the garlic and red pepper flakes and cook until the garlic just begins to turn golden at the edges, 30 seconds to 1 minute. Add the wine, bring to a simmer and cook until reduced by half, about 2 minutes. Remove from the heat.  \r\nMeanwhile, cook the pasta until very al dente, reserving 1 cup of the pasta water. Add the pasta and 3/4 cup pasta water to the skillet along with the chicken, lemon zest and juice and the remaining 4 tablespoons butter. Return the skillet to medium-low heat and gently stir the pasta until the butter is melted, adding the remaining 1/4 pasta water if the pasta seems too dry. Remove the skillet from the heat, sprinkle with the grated cheese and parsley and toss before serving.', 'Delicious chicken scampi pasta.', 'https://www.foodnetwork.com/recipes/food-network-kitchen/chicken-scampi-pasta-5588113', '5fdb9d26da8b8.jpeg', 47),
('Potato Latkes', 'Ina Garten', 'Easy', 10, 10, 20, 2, '2 large baking potatoes\r\n1 extra-large egg, whisked\r\n3 tablespoons all-purpose flour\r\n1 1/4 teaspoons kosher salt\r\n1/4 teaspoon freshly ground black pepper\r\n3 tablespoons clarified butter', 'Peel the potatoes and grate them on a box grater. Wrap the grated potatoes in a kitchen towel and squeeze out as much liquid as possible. Combine the potatoes in a bowl with the egg, flour, salt and pepper. Mix well.\r\nMelt the clarified butter in a large saute pan over medium heat. Place a tablespoon of the potato mixture into the sizzling butter and cook for 2 minutes. Turn the pancakes over and cook for another 2 minutes, or until crisp on the outside and golden brown. Serve the pancakes hot from the skillet.\r\n', 'Delicious potato latkes that aren\'t challenging to make.', 'https://www.foodnetwork.com/recipes/ina-garten/potato-latkes-recipe-2041639', '5fdb9db82e5c8.jpeg', 48),
('Potato Casserole', 'Trisha Yearwood', 'Easy', 20, 25, 45, 8, 'Nonstick cooking spray, for greasing the baking dish\r\n6 large russet potatoes \r\nPinch salt \r\n8 ounces sliced bacon \r\n1 cup milk \r\n1/2 cup mayonnaise \r\n1/2 cup sour cream \r\n1/4 cup (1/2 stick) unsalted butter \r\nPinch garlic salt \r\nPinch freshly ground black pepper \r\n2 cups grated Cheddar', 'Preheat the oven to 400 degrees F. Grease a 2-quart baking dish with cooking spray.\r\nPeel the potatoes and cut them into 1-inch cubes. Place the potatoes and salt in a pressure cooker with water to cover and bring to a boil. Reduce the heat and simmer the potatoes until very tender, about 5 minutes. (If you do not have a pressure cooker, boil the potatoes in a pot of water with a pinch of salt until tender, about 20 minutes.)\r\nWhile the potatoes boil, cook the bacon in a medium skillet over medium heat until browned and cooked through, 8 to 10 minutes. Drain the bacon on paper towels and, when cool enough to handle, crumble it into small pieces. Set aside.\r\nAdd the milk, mayonnaise, sour cream, butter, garlic salt, pepper and 1 cup of the cheese to a stand mixer with a paddle attachment. Whip the mixture until thoroughly combined. Drain the potatoes and add to the mixer. Mix again to combine and the potatoes are whipped smooth.\r\nSpoon the mixture into the prepared baking dish. Sprinkle the crumbled bacon and remaining 1 cup cheese over the top and bake until the cheese is melted and the casserole is heated through, about 20 minutes.', 'Delicious and hearty potato casserole.', 'https://www.foodnetwork.com/recipes/trisha-yearwood/potato-casserole-2791023', '5fdb9e8d93eab.jpeg', 49),
('The Best Sweet Potato  Salad', 'Jeff Mauro', 'Easy', 20, 20, 40, 6, '1/4 cup chopped cornichons or relish\r\n2 tablespoons whole-grain mustard\r\n1 tablespoon honey \r\n2 ribs celery, diced \r\nZest and juice from 1 lemon\r\n1/2 small red onion, minced\r\nKosher salt and freshly ground black pepper \r\n2 pounds sweet potatoes, peeled and cut into 1-inch cubes \r\n1/4 cup white vinegar \r\n1/2 cup mayonnaise\r\n2 tablespoons minced fresh chives, plus more for garnish \r\n2 tablespoons minced fresh parsley, plus more for garnish', 'In a bowl, mix together the cornichons or relish, mustard, honey, celery, lemon zest and juice and red onion. Season with salt and pepper and let sit while the potatoes cook.\r\nPut the potatoes in a large saucepan and add enough cold water to cover by 1 inch. Season the water generously with salt. Bring to a boil over medium-high heat. Reduce the heat to a simmer and cook until the potatoes are tender, about 10 minutes.\r\nDrain the potatoes in a colander, put back in the saucepan, add the vinegar and, using a rubber spatula, toss gently to combine.\r\nAdd the mayonnaise, chives and parsley to the celery-onion mixture and stir to combine. Add the warm potatoes to the dressing and toss. Season to taste. Garnish with extra chives and parsley.', 'Sweet Potato Salad that is sweet to eat.', 'https://www.foodnetwork.com/recipes/jeff-mauro/the-best-sweet-potato-potato-salad-5342470', '5fdb9f7eeb59a.jpeg', 50),
('Mashed Potato Cakes', 'Sara Moulton', 'Easy', 5, 20, 25, 4, '2 cups chilled mashed potatoes\r\n2 tablespoons vegetable oil\r\n2 tablespoons unsalted butter\r\n1/2 cup all-purpose flour, for dredging\r\n1 1/2 teaspoons kosher salt\r\n1/4 teaspoon freshly ground black pepper', 'Divide the mashed potatoes into 8 equal portions. Use your hands to form 1/2-inch thick patties.\r\nHeat the oil with the butter in a large nonstick skillet over medium-high heat until almost smoking. Mix the flour with the salt and pepper in a pie plate. Coat the potato patties in the flour mixture. Add the potato cakes to the pan and reduce the heat to medium-low. Cook until they have formed a golden crust, 15 to 20 minutes. (Peek underneath using a spatula before turning.) Turn and cook the other side until golden brown, about 15 minutes. Season with additional salt and pepper and serve hot.', 'Incredible mashed potato cakes.', 'https://www.foodnetwork.com/recipes/mashed-potato-cakes-recipe-1914715', '5fdba007b6aa6.jpeg', 51),
('Cloud Eggs', 'Food Network Kitchen', 'Easy', 10, 10, 20, 4, 'Nonstick cooking spray\r\n4 large eggs\r\nKosher salt\r\n4 slices buttered brioche toast, for serving', 'Preheat the oven to 350 degrees F. Line a baking sheet with parchment and coat with nonstick cooking spray.\r\nCoat 4 small bowls with nonstick cooking spray. Separate the eggs and put the whites into a medium bowl and the yolks in the small bowls (1 yolk per bowl). Add a large pinch of salt to the egg whites and beat with an electric mixer on low speed until stiff peaks form, 2 to 3 minutes.\r\nDollop 4 large spoonfuls of the egg whites onto the prepared baking sheet and make a small well in the middle of each with the back of a spoon. Bake the whites until they are firm, no longer wet and just beginning to turn brown, about 6 minutes. Gently pour 1 yolk into the well of each white. Bake until the edges of the yolk just start to set while still being runny, 3 to 4 minutes. Season with salt.\r\nServe on top of buttered brioche toast.', 'Very aesthetically pleasing and very tasty.', 'https://www.foodnetwork.com/recipes/food-network-kitchen/cloud-eggs-3744344', '5fdba13beef6a.jpeg', 52),
('Fried Egg Sandwhich', 'Claire Thomas', 'Easy', 0, 20, 20, 1, '1 tablespoon ketchup\r\n1/2 teaspoon chipotle in adobo sauce\r\n2 slices sourdough bread\r\n2 slices Cheddar\r\n1 tablespoon unsalted butter\r\n1 slice bacon, halved \r\n1 egg', 'Combine the ketchup and chipotle and spread on the inside of each piece of bread. Place the cheese between the bread at an angle so that the edges hangover the sides of the bread. Butter the outside of one bread slice with half the butter. Heat a skillet over medium heat. Press the sandwich on, buttered-side down. Press until the bread is golden brown and the cheese has started to melt. Butter the other side (which is facing up) with the remaining butter and flip. Cook until golden brown and the cheese is gooey, this should all take 3 to 4 minutes. Remove the sandwich from the heat and hold.\r\nMeanwhile, in a pan over medium heat, cook the bacon until barely crisp, about 5 minutes. Flip the bacon, pushing the two pieces next to each other to form a square. Crack the egg on top, cooking into the bacon. Continue cooking until the egg is set, about 5 minutes. Open up the sandwich (use a spoon to help pull apart the bread) and slide in the eggs and bacon. Close up, slice and enjoy.', 'Quick, easy and tasty egg sandwich.', 'https://www.foodnetwork.com/recipes/fried-egg-sandwich-3529179', '5fdba1d47e184.jpeg', 53),
('Perfect Sunny-Side-Up Eggs', 'Jeff Mauro', 'Easy', 10, 5, 15, 1, '1 teaspoon olive oil\r\n2 large eggs \r\nToast, for serving, optional\r\nKosher salt and freshly ground black pepper', 'Heat the oil in a medium nonstick skillet over low heat until slightly shimmering, about 5 minutes. Crack an egg into a small ramekin and slowly add it to the skillet; repeat with the other egg, adding it to the other side of the skillet. Cover with a tight lid and cook, uninterrupted, until the whites are completely set but the yolks are still runny, 2 to 2 1/2 minutes. Slide the eggs out of the skillet onto a plate or toast. Season with salt and pepper.', 'The perfect sunny-side-up-eggs that leave you wanting more.', 'https://www.foodnetwork.com/recipes/jeff-mauro/perfect-sunny-side-up-eggs-3672187', '5fdba26c359c6.jpeg', 54),
('Sheet Pan Eggs', 'Food Network Kitchen', 'Easy', 10, 10, 20, 12, 'Olive oil, for the pan\r\n12 large eggs \r\nKosher salt and freshly ground black pepper\r\n', 'Preheat the oven to 425 degrees F. Generously coat a quarter-sheet pan with oil and place in the oven to heat for 15 minutes.\r\nCrack the eggs carefully into a pitcher. Remove the sheet pan from the oven and, working quickly, gently pour the eggs into the pan. Sprinkle with salt and pepper and carefully return to the oven. Bake until the egg whites are just set but the yolks are still runny, about 5 minutes, or to the desired degree of doneness.\r\n', 'Never play short-order cook to a group of friends with this easy hack that guarantees everyone\'s breakfast is done at the same time.', 'https://www.foodnetwork.com/recipes/food-network-kitchen/sheet-pan-eggs-4703292', '5fdba3024a696.jpeg', 55),
('Caprese Salad', 'Rachael Ray', 'Easy', 9, 1, 10, 6, '3 vine-ripe tomatoes, 1/4-inch thick slices\r\n1 pound fresh mozzarella, 1/4-inch thick slices\r\n20 to 30 leaves (about 1 bunch) fresh basil\r\nExtra-virgin olive oil, for drizzling\r\nCoarse salt and pepper', 'Layer alternating slices of tomatoes and mozzarella, adding a basil leaf between each, on a large, shallow platter. Drizzle the salad with extra-virgin olive oil and season with salt and pepper, to taste.\r\n', 'Quick and easy Caprese Salad', 'https://www.foodnetwork.com/recipes/rachael-ray/caprese-salad-recipe-1939232', '5fdba38eb08b3.jpeg', 56);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `recipeapp`
--
ALTER TABLE `recipeapp`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `recipeapp`
--
ALTER TABLE `recipeapp`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=57;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
